# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trip_creater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   
  pod 'HEREMaps'
  pod 'RealmSwift'
  pod 'SnapKit' 
  
  # Pods for trip_creater

end
